[package]
name = "simplez_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplez_common = { path = "../common" }
serde = { version = "1", features = ["derive"] }